# Generated by Django 5.0.7 on 2024-07-26 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="bank_address",
            field=models.CharField(default=1, max_length=225),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="account",
            name="pin",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="statement",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
