# Generated by Django 5.0.7 on 2024-07-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank_app", "0003_statement_transaction_type_alter_statement_account"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="statement",
            name="transaction_type",
        ),
        migrations.AddField(
            model_name="account",
            name="branch_name",
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
